In [60]:
import numpy as np
# run this first

In [61]:
A = np.array ([[1,0,2],
               [0,1,0],
               [0,0,1]     # this row will always be 0, 0, 1 for DH parameters
               ])

# this is the tranlation matrix in DH paramter form.
# For the first arm, arm length (L1) = 2

In [69]:
a = np.array ([[0],
               [1],
               [1]])

# this is the starting position (0,1, z=1).
# We need this z=1 in the vector space (and matrix) so our math could work.

In [70]:
A @ a

# after this opeartion, we should step forward in the L1-direction for 2.

array([[2],
       [1],
       [1]])

In [71]:
B = np.array ([[1,0,0],
               [0,1,4],
               [0,0,1]
               ])
# this is the tranlation matrix for the second arm, L2 = 4

In [73]:
B@A@a

# with this opereration, we stepped 2 in the L1 direction and 4 in the L2 direction.
# [new posiiton]=[B][A][old position]

array([[2],
       [5],
       [1]])

Now it's time to add our old friend back, the euler rotation

In [74]:
#       If we rotate pi/4 degree                             This is the form of:
A_rot = np.array ([[np.cos(np.pi/4), -np.sin(np.pi/4),  0], # ([[cos(),-sin(), 0],
                   [np.sin(np.pi/4),  np.cos(np.pi/4),  0], #.  [sin(),cos(),  0],
                   [0,                    0,        1]      #   [0,     0,     1]
                  ])                                        # written in numpy

In [75]:
new_A = A @ A_rot @ a
print ('First rotation then translation will get:')
print (new_A)
print ()

new_A_2 = A_rot @ A @ a
print ('First translation then rotatoin will get:')
print (new_A_2)

# new_A position will be different from new_A_2 position!

First rotation then translation will get:
[[1.29289322]
 [0.70710678]
 [1.        ]]

First translation then rotatoin will get:
[[0.70710678]
 [2.12132034]
 [1.        ]]


So for the full arm, we are going to need:


$$
[New position] =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & L2 \\
0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
\cos\theta_2 & -\sin\theta_2 & 0 \\
\sin\theta_2 & \cos\theta_2 & 0 \\
0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
1 & 0 & L1 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
\cos\theta_1 & -\sin\theta_1 & 0 \\
\sin\theta_1 & \cos\theta_1 & 0 \\
0 & 0 & 1
\end{bmatrix}
[Old position]
$$

where four matrix multiply into each other sequentially.

